spring:
  config:
    # اگر می‌خواهی اپ حتی اگر Config Server در دسترس نبود بالا بیاید از optional استفاده کن.
    import: "optional:configserver:"
  application:
    name: order-service

  cloud:
    config:
      uri: http://localhost:9090    # آدرس Config Server
      fail-fast: true               # اگر می‌خواهی در صورت عدم دسترسی فوراً خطا بدهد؛ در حالت optional می‌توان false گذاشت

# بقیه تنظیمات اپ (مثال)
server:
  port: 8086
