server:
  port: 8081 # ???? ?????

spring:
  application:
    name: product-service # ??? ???? ???? ??????? ?? ??????
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud10?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update         # یا validate/create-drop بسته به نیازتان
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8088/eureka/# ???? ???? ??????
    healthcheck:
      enabled: true