server:
  port: 9090

spring:
  application:
    name: config-server

  cloud:
    config:
      # ??? ????????? ??? ?? ?????? ???? ?????? ?? ?????:
      import-check:
        enabled: false

      server:
        encrypt:
          enabled: true
        git:
          uri: https://github.com/amir-masoud-mohamadi/config-repo
          search-paths: '{application}'   # ?????? ???? ??????? ?? ??? ???????? ???? repo ????
          clone-on-start: true
          default-label: master           # ?? main ?? ?? ??????? ?? ?? repo ???? ????
          # ??? ???? ????? ???? ?? ????? ????? ??????? ?? (?? ??? ???????? ???? ???? ????):
          # username: ${GIT_USERNAME}
          # password: ${GIT_TOKEN}
