server:
  port: 8083 # ???? ?????
spring:
  application:
    name: order-service # ??? ???? ???? ??????? ?? ??????
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud10?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update         # یا validate/create-drop بسته به نیازتان
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    metadata-map:
      version: 2.1.0
      region: tehran
      weight: 1 # برای Load Balancing
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8088/eureka/# ???? ???? ??????
    healthcheck:
      enabled: true